In [1]:
#Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#reading the dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset = pd.get_dummies(dataset,drop_first = True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age','bmi','children','sex_male','smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid = {
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, cv=5)

#fitting the model for grid search
grid.fit(indep,dep)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

In [9]:
#print the best parameter after tuning 
#print(grid.best_params_)

In [10]:
re=grid.cv_results_

print("The R_score value for best parameter{} :".format (grid.best_params_))

The R_score value for best parameter{'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2} :

In [11]:
table = pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006425,0.007871,0.003002,0.006003,None,1,2,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",0.727327,0.614271,0.737081,0.692074,0.685620,0.691274,0.043267,27
1,0.003124,0.006249,0.003127,0.006255,None,1,5,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",0.745124,0.698023,0.764802,0.742466,0.753243,0.740732,0.022725,25
2,0.006249,0.007654,0.000000,0.000000,None,1,10,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",0.831445,0.728170,0.798664,0.779250,0.784032,0.784312,0.033482,19
3,0.005801,0.007215,0.000337,0.000675,None,2,2,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",0.756053,0.658828,0.821461,0.776558,0.791848,0.760950,0.055340,24
4,0.003127,0.006253,0.003124,0.006248,None,2,5,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",0.770802,0.695497,0.821545,0.779661,0.801404,0.773782,0.042933,22
5,0.006366,0.007799,0.000000,0.000000,None,2,10,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",0.832305,0.742478,0.842226,0.791790,0.806676,0.803095,0.035212,17
6,0.000000,0.000000,0.003147,0.006294,None,4,2,"{'max_depth': None, 'min_samples_leaf': 4, 'mi...",0.831745,0.741364,0.848966,0.801012,0.815199,0.807657,0.036831,14
7,0.006230,0.007630,0.000000,0.000000,None,4,5,"{'max_depth': None, 'min_samples_leaf': 4, 'mi...",0.831745,0.741364,0.847879,0.801012,0.815199,0.807440,0.036589,15
8,0.000000,0.000000,0.000000,0.000000,None,4,10,"{'max_depth': None, 'min_samples_leaf': 4, 'mi...",0.840554,0.742407,0.852427,0.808309,0.815293,0.811798,0.038255,11
9,0.000000,0.000000,0.003125,0.006249,5,1,2,"{'max_depth': 5, 'min_samples_leaf': 1, 'min_s...",0.871181,0.780551,0.874556,0.822363,0.861296,0.841989,0.035904,7
10,0.000000,0.000000,0.003125,0.006249,5,1,5,"{'max_depth': 5, 'min_samples_leaf': 1, 'min_s...",0.871005,0.780551,0.874556,0.822363,0.861384,0.841972,0.035885,9
11,0.000000,0.000000,0.006273,0.006125,5,1,10,"{'max_depth': 5, 'min_samples_leaf': 1, 'min_s...",0.871005,0.780572,0.874556,0.822363,0.861384,0.841976,0.035877,8
12,0.003126,0.006252,0.000000,0.000000,5,2,2,"{'max_depth': 5, 'min_samples_leaf': 2, 'min_s...",0.869463,0.780780,0.886406,0.830459,0.863010,0.846024,0.037330,6
13,0.003124,0.006249,0.000000,0.000000,5,2,5,"{'max_depth': 5, 'min_samples_leaf': 2, 'min_s...",0.869476,0.780780,0.886406,0.830459,0.863338,0.846092,0.037361,4
14,0.006249,0.007654,0.000000,0.000000,5,2,10,"{'max_depth': 5, 'min_samples_leaf': 2, 'min_s...",0.869476,0.780573,0.886406,0.830459,0.863338,0.846050,0.037434,5
15,0.000183,0.000366,0.000000,0.000000,5,4,2,"{'max_depth': 5, 'min_samples_leaf': 4, 'min_s...",0.868761,0.780662,0.888991,0.840098,0.862521,0.848206,0.037199,1
16,0.003182,0.006363,0.003004,0.006009,5,4,5,"{'max_depth': 5, 'min_samples_leaf': 4, 'min_s...",0.868761,0.780662,0.888991,0.840098,0.862521,0.848206,0.037199,1
17,0.003127,0.006254,0.000000,0.000000,5,4,10,"{'max_depth': 5, 'min_samples_leaf': 4, 'min_s...",0.868761,0.780662,0.888991,0.840098,0.862521,0.848206,0.037199,1
18,0.003125,0.006250,0.003125,0.006250,10,1,2,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",0.771043,0.665281,0.751686,0.718919,0.767571,0.734900,0.039389,26
19,0.006365,0.007814,0.000000,0.000000,10,1,5,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",0.776902,0.705101,0.790034,0.757241,0.790127,0.763881,0.031754,23
20,0.003144,0.006289,0.003108,0.006215,10,1,10,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",0.837347,0.730991,0.802846,0.779657,0.803882,0.790945,0.035168,18
21,0.003125,0.006250,0.003124,0.006249,10,2,2,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.784017,0.687129,0.834314,0.780513,0.818818,0.780958,0.051174,21
22,0.006252,0.007657,0.000000,0.000000,10,2,5,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.787617,0.696947,0.831311,0.780850,0.821974,0.783740,0.047500,20
23,0.006249,0.007654,0.000000,0.000000,10,2,10,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.838438,0.744733,0.846715,0.791672,0.813966,0.807105,0.036678,16
24,0.006247,0.007651,0.000000,0.000000,10,4,2,"{'max_depth': 10, 'min_samples_leaf': 4, 'min_...",0.835409,0.741257,0.854924,0.801813,0.823142,0.811309,0.039040,13
25,0.003125,0.006249,0.000000,0.000000,10,4,5,"{'max_depth': 10, 'min_samples_leaf': 4, 'min_...",0.835409,0.741257,0.856011,0.801813,0.823142,0.811526,0.039284,12
26,0.006368,0.007801,0.000101,0.000202,10,4,10,"{'max_depth': 10, 'min_samples_leaf': 4, 'min_...",0.844316,0.742722,0.857306,0.809146,0.822519,0.815202,0.039910,10

In [13]:
age_input = float(input("Age :"))
bmi_input = float(input("BMI :"))
children_input = float(input("Children :"))
sex_male_input = int(input("Sex_Male 0 or 1 :"))
smoker_yes_input = int(input("Smoker Yes0 or 1:"))

Age :19
BMI :27
Children :0
Sex_Male 0 or 1 :0
Smoker Yes0 or 1:0

In [14]:
# change the parameter
Future_prediction = grid.predict([[age_input,bmi_input, children_input, sex_male_input, smoker_yes_input]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [15]:
print("Future_Prediction = {}".format(Future_prediction))

Future_Prediction = [2585.69774966]