In [1]:
#Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#reading the dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset = pd.get_dummies(dataset,drop_first = True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age','bmi','children','sex_male','smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','linear','sigmoid'],
             'C':[10,100,1000,2000,3000]}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

#fitting the model for grid search
grid.fit(indep,dep)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
Fitting 5 folds for each of 20 candidates, totalling 100 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'kernel': ['rbf', 'poly', 'linear', 'sigmoid']},
             verbose=3)

In [9]:
#print the best parameter after tuning 
#print(grid.best_params_)

In [10]:
re=grid.cv_results_

print("The R_score value for best parameter{} :".format (grid.best_params_))

The R_score value for best parameter{'C': 1000, 'kernel': 'linear'} :

In [11]:
table = pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.266814,0.010774,0.158205,0.014495,10,rbf,"{'C': 10, 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,9
1,0.214801,0.014147,0.044150,0.006503,10,poly,"{'C': 10, 'kernel': 'poly'}",-0.125153,-0.081505,-0.111907,-0.131602,-0.179328,-0.125899,0.031794,12
2,0.232418,0.017589,0.034619,0.007622,10,linear,"{'C': 10, 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,6
3,0.294452,0.008016,0.058929,0.012444,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,10
4,0.240710,0.028613,0.145039,0.011524,100,rbf,"{'C': 100, 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,17
5,0.228572,0.006521,0.044239,0.004733,100,poly,"{'C': 100, 'kernel': 'poly'}",-0.132885,-0.082461,-0.129220,-0.139962,-0.189219,-0.134749,0.033948,14
6,0.485434,0.025336,0.037498,0.007654,100,linear,"{'C': 100, 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,4
7,0.307049,0.012569,0.069013,0.007648,100,sigmoid,"{'C': 100, 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,15
8,0.278446,0.010216,0.150203,0.012374,1000,rbf,"{'C': 1000, 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,16
9,0.301136,0.011820,0.043963,0.006327,1000,poly,"{'C': 1000, 'kernel': 'poly'}",-0.080527,-0.028469,-0.073376,-0.086611,-0.134493,-0.080695,0.033795,8
10,1.422226,0.140895,0.040256,0.005477,1000,linear,"{'C': 1000, 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
11,0.281885,0.021186,0.048888,0.008793,1000,sigmoid,"{'C': 1000, 'kernel': 'sigmoid'}",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,18
12,0.234603,0.027361,0.112558,0.011788,2000,rbf,"{'C': 2000, 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,13
13,0.332677,0.063672,0.039116,0.004974,2000,poly,"{'C': 2000, 'kernel': 'poly'}",-0.020567,0.035685,-0.011468,-0.024587,-0.076360,-0.019459,0.035693,7
14,2.937375,0.206203,0.034054,0.006513,2000,linear,"{'C': 2000, 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,2
15,0.354123,0.014820,0.084639,0.016065,2000,sigmoid,"{'C': 2000, 'kernel': 'sigmoid'}",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,19
16,0.353889,0.011283,0.188289,0.021065,3000,rbf,"{'C': 3000, 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,11
17,0.525854,0.070842,0.037695,0.007658,3000,poly,"{'C': 3000, 'kernel': 'poly'}",0.037700,0.098496,0.049291,0.035615,-0.020924,0.040035,0.038064,5
18,6.217285,1.568778,0.047480,0.024119,3000,linear,"{'C': 3000, 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,3
19,0.394659,0.039749,0.084323,0.018706,3000,sigmoid,"{'C': 3000, 'kernel': 'sigmoid'}",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,20

In [13]:
age_input = float(input("Age :"))
bmi_input = float(input("BMI :"))
children_input = float(input("Children :"))
sex_male_input = int(input("Sex_Male 0 or 1 :"))
smoker_yes_input = int(input("Smoker Yes0 or 1:"))

Age :19
BMI :27
Children :0
Sex_Male 0 or 1 :0
Smoker Yes0 or 1:0

In [14]:
# change the parameter
Future_prediction = grid.predict([[age_input,bmi_input, children_input, sex_male_input, smoker_yes_input]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [15]:
print("Future_Prediction = {}".format(Future_prediction))

Future_Prediction = [1399.96817615]